# Generated by Django 5.0.14 on 2026-09-13 19:41

import apps.devices.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('fridge', 'Smart Fridge'), ('gas', 'Smart Gas'), ('vehicle', 'Smart Vehicle'), ('home_office', 'Smart Home / Office')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('location_label', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending activation'), ('online', 'Online'), ('offline', 'Offline')], default='pending', max_length=20)),
                ('is_armed', models.BooleanField(default=False, help_text='Security-relevant devices (vehicle, home/office) can be armed.')),
                ('pairing_code', models.CharField(default=apps.devices.models.generate_pairing_code, max_length=20, unique=True)),
                ('install_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Set for organization (B2B) devices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Set for individual (B2C) devices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'metric', '-timestamp'], name='devices_sen_device__66b646_idx')],
            },
        ),
    ]
